source 'https://rubygems.org'

gem 'capybara'
gem 'ejs'
gem 'ffaker'
gem 'inifile'
gem 'launchy'
gem 'md2man'
gem 'middleman'
gem 'middleman-core'
gem 'middleman-react'
gem 'oj' # faster JS compiles
gem 'pg'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'scrypt'
gem 'selenium-webdriver'
gem 'sequel'
gem 'therubyracer' # faster JS compiles
