#!/bin/sh

set -e

# Make sure the tpr user exists
if ! getent passwd tpr > /dev/null; then
    adduser --system --quiet --home / --no-create-home \
        --shell /bin/sh --group --gecos "The Pithy Reader" tpr
fi
# if the user was created manually, make sure the group is there as well
if ! getent group tpr > /dev/null; then
    addgroup --system --quiet tpr
fi
# make sure tpr is in the tpr group
if ! id -Gn tpr | grep -qw tpr; then
    adduser --quiet tpr tpr
fi

# check validity of tpr user and group
if [ "`id -u tpr`" -eq 0 ]; then
    echo "The tpr system user must not have uid 0 (root).
Please fix this and reinstall this package." >&2
    exit 1
fi
if [ "`id -g tpr`" -eq 0 ]; then
    echo "The tpr system user must not have root as primary group.
Please fix this and reinstall this package." >&2
    exit 1
fi

chown -R tpr:tpr /etc/tpr
chmod 740 /etc/tpr
chmod 640 /etc/tpr/config.yml
