package data

// This file is automatically generated by pgxdata.

import (
	"context"
	"strings"

	"errors"

	"github.com/jackc/pgsql"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID              pgtype.Int4
	Name            pgtype.Text
	URL             pgtype.Text
	LastFetchTime   pgtype.Timestamptz
	ETag            pgtype.Text
	LastFailure     pgtype.Text
	LastFailureTime pgtype.Timestamptz
	FailureCount    pgtype.Int4
	CreationTime    pgtype.Timestamptz
}

const countFeedSQL = `select count(*) from "feeds"`

func CountFeed(ctx context.Context, db Queryer) (int64, error) {
	var n int64
	err := db.QueryRow(ctx, countFeedSQL).Scan(&n)
	return n, err
}

const SelectAllFeedSQL = `select
  "id",
  "name",
  "url",
  "last_fetch_time",
  "etag",
  "last_failure",
  "last_failure_time",
  "failure_count",
  "creation_time"
from "feeds"`

func SelectAllFeed(ctx context.Context, db Queryer) ([]Feed, error) {
	var rows []Feed

	dbRows, err := db.Query(ctx, SelectAllFeedSQL)
	if err != nil {
		return nil, err
	}

	for dbRows.Next() {
		var row Feed
		dbRows.Scan(
			&row.ID,
			&row.Name,
			&row.URL,
			&row.LastFetchTime,
			&row.ETag,
			&row.LastFailure,
			&row.LastFailureTime,
			&row.FailureCount,
			&row.CreationTime,
		)
		rows = append(rows, row)
	}

	if dbRows.Err() != nil {
		return nil, dbRows.Err()
	}

	return rows, nil
}

const selectFeedByPKSQL = `select
  "id",
  "name",
  "url",
  "last_fetch_time",
  "etag",
  "last_failure",
  "last_failure_time",
  "failure_count",
  "creation_time"
from "feeds"
where "id"=$1`

func SelectFeedByPK(
	ctx context.Context,
	db Queryer,
	id int32,
) (*Feed, error) {
	var row Feed
	err := db.QueryRow(ctx, selectFeedByPKSQL, id).Scan(
		&row.ID,
		&row.Name,
		&row.URL,
		&row.LastFetchTime,
		&row.ETag,
		&row.LastFailure,
		&row.LastFailureTime,
		&row.FailureCount,
		&row.CreationTime,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	} else if err != nil {
		return nil, err
	}

	return &row, nil
}

func InsertFeed(ctx context.Context, db Queryer, row *Feed) error {
	args := pgsql.Args{}

	var columns, values []string

	columns = append(columns, `name`)
	values = append(values, args.Use(&row.Name).String())
	columns = append(columns, `url`)
	values = append(values, args.Use(&row.URL).String())
	columns = append(columns, `last_fetch_time`)
	values = append(values, args.Use(&row.LastFetchTime).String())
	columns = append(columns, `etag`)
	values = append(values, args.Use(&row.ETag).String())
	columns = append(columns, `last_failure`)
	values = append(values, args.Use(&row.LastFailure).String())
	columns = append(columns, `last_failure_time`)
	values = append(values, args.Use(&row.LastFailureTime).String())
	columns = append(columns, `failure_count`)
	values = append(values, args.Use(&row.FailureCount).String())
	columns = append(columns, `creation_time`)
	values = append(values, args.Use(&row.CreationTime).String())

	sql := `insert into "feeds"(` + strings.Join(columns, ", ") + `)
values(` + strings.Join(values, ",") + `)
returning "id"
  `

	return db.QueryRow(ctx, sql, args.Values()...).Scan(&row.ID)
}

func UpdateFeed(ctx context.Context, db Queryer,
	id int32,
	row *Feed,
) error {
	sets := make([]string, 0, 9)
	args := pgsql.Args{}

	sets = append(sets, `name`+"="+args.Use(&row.Name).String())
	sets = append(sets, `url`+"="+args.Use(&row.URL).String())
	sets = append(sets, `last_fetch_time`+"="+args.Use(&row.LastFetchTime).String())
	sets = append(sets, `etag`+"="+args.Use(&row.ETag).String())
	sets = append(sets, `last_failure`+"="+args.Use(&row.LastFailure).String())
	sets = append(sets, `last_failure_time`+"="+args.Use(&row.LastFailureTime).String())
	sets = append(sets, `failure_count`+"="+args.Use(&row.FailureCount).String())
	sets = append(sets, `creation_time`+"="+args.Use(&row.CreationTime).String())

	if len(sets) == 0 {
		return nil
	}

	sql := `update "feeds" set ` + strings.Join(sets, ", ") + ` where ` + `"id"=` + args.Use(id).String()

	commandTag, err := db.Exec(ctx, sql, args.Values()...)
	if err != nil {
		return err
	}
	if commandTag.RowsAffected() != 1 {
		return ErrNotFound
	}
	return nil
}

func DeleteFeed(ctx context.Context, db Queryer,
	id int32,
) error {
	args := pgsql.Args{}

	sql := `delete from "feeds" where ` + `"id"=` + args.Use(id).String()

	commandTag, err := db.Exec(ctx, sql, args.Values()...)
	if err != nil {
		return err
	}
	if commandTag.RowsAffected() != 1 {
		return ErrNotFound
	}
	return nil
}
