package data

// This file is automatically generated by pgxdata.

import (
	"strings"

	"github.com/jackc/pgx"
)

type Session struct {
	ID        Bytes
	UserID    Int32
	StartTime Time
}

const countSessionSQL = `select count(*) from "sessions"`

func CountSession(db Queryer) (int64, error) {
	var n int64
	err := prepareQueryRow(db, "pgxdataCountSession", countSessionSQL).Scan(&n)
	return n, err
}

const SelectAllSessionSQL = `select
  "id",
  "user_id",
  "start_time"
from "sessions"`

func SelectAllSession(db Queryer) ([]Session, error) {
	var rows []Session

	dbRows, err := prepareQuery(db, "pgxdataSelectAllSession", SelectAllSessionSQL)
	if err != nil {
		return nil, err
	}

	for dbRows.Next() {
		var row Session
		dbRows.Scan(
			&row.ID,
			&row.UserID,
			&row.StartTime,
		)
		rows = append(rows, row)
	}

	if dbRows.Err() != nil {
		return nil, dbRows.Err()
	}

	return rows, nil
}

const selectSessionByPKSQL = `select
  "id",
  "user_id",
  "start_time"
from "sessions"
where "id"=$1`

func SelectSessionByPK(
	db Queryer,
	id []byte,
) (*Session, error) {
	var row Session
	err := prepareQueryRow(db, "pgxdataSelectSessionByPK", selectSessionByPKSQL, id).Scan(
		&row.ID,
		&row.UserID,
		&row.StartTime,
	)
	if err == pgx.ErrNoRows {
		return nil, ErrNotFound
	} else if err != nil {
		return nil, err
	}

	return &row, nil
}

func InsertSession(db Queryer, row *Session) error {
	args := pgx.QueryArgs(make([]interface{}, 0, 3))

	var columns, values []string

	row.ID.addInsert(`id`, &columns, &values, &args)
	row.UserID.addInsert(`user_id`, &columns, &values, &args)
	row.StartTime.addInsert(`start_time`, &columns, &values, &args)

	sql := `insert into "sessions"(` + strings.Join(columns, ", ") + `)
values(` + strings.Join(values, ",") + `)
returning "id"
  `

	psName := preparedName("pgxdataInsertSession", sql)

	return prepareQueryRow(db, psName, sql, args...).Scan(&row.ID)
}

func UpdateSession(db Queryer,
	id []byte,
	row *Session,
) error {
	sets := make([]string, 0, 3)
	args := pgx.QueryArgs(make([]interface{}, 0, 3))

	row.ID.addUpdate(`id`, &sets, &args)
	row.UserID.addUpdate(`user_id`, &sets, &args)
	row.StartTime.addUpdate(`start_time`, &sets, &args)

	if len(sets) == 0 {
		return nil
	}

	sql := `update "sessions" set ` + strings.Join(sets, ", ") + ` where ` + `"id"=` + args.Append(id)

	psName := preparedName("pgxdataUpdateSession", sql)

	commandTag, err := prepareExec(db, psName, sql, args...)
	if err != nil {
		return err
	}
	if commandTag.RowsAffected() != 1 {
		return ErrNotFound
	}
	return nil
}

func DeleteSession(db Queryer,
	id []byte,
) error {
	args := pgx.QueryArgs(make([]interface{}, 0, 1))

	sql := `delete from "sessions" where ` + `"id"=` + args.Append(id)

	commandTag, err := prepareExec(db, "pgxdataDeleteSession", sql, args...)
	if err != nil {
		return err
	}
	if commandTag.RowsAffected() != 1 {
		return ErrNotFound
	}
	return nil
}
