package data

// This file is automatically generated by pgxdata.

import (
	"context"
	"net/netip"
	"strings"

	"errors"

	"github.com/jackc/pgsql"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type PasswordReset struct {
	Token          pgtype.Text
	Email          pgtype.Text
	RequestIP      netip.Addr
	RequestTime    pgtype.Timestamptz
	UserID         pgtype.Int4
	CompletionIP   netip.Addr
	CompletionTime pgtype.Timestamptz
}

const countPasswordResetSQL = `select count(*) from "password_resets"`

func CountPasswordReset(ctx context.Context, db Queryer) (int64, error) {
	var n int64
	err := db.QueryRow(ctx, countPasswordResetSQL).Scan(&n)
	return n, err
}

const SelectAllPasswordResetSQL = `select
  "token",
  "email",
  "request_ip",
  "request_time",
  "user_id",
  "completion_ip",
  "completion_time"
from "password_resets"`

func SelectAllPasswordReset(ctx context.Context, db Queryer) ([]PasswordReset, error) {
	var rows []PasswordReset

	dbRows, err := db.Query(ctx, SelectAllPasswordResetSQL)
	if err != nil {
		return nil, err
	}

	for dbRows.Next() {
		var row PasswordReset
		dbRows.Scan(
			&row.Token,
			&row.Email,
			&row.RequestIP,
			&row.RequestTime,
			&row.UserID,
			&row.CompletionIP,
			&row.CompletionTime,
		)
		rows = append(rows, row)
	}

	if dbRows.Err() != nil {
		return nil, dbRows.Err()
	}

	return rows, nil
}

const selectPasswordResetByPKSQL = `select
  "token",
  "email",
  "request_ip",
  "request_time",
  "user_id",
  "completion_ip",
  "completion_time"
from "password_resets"
where "token"=$1`

func SelectPasswordResetByPK(
	ctx context.Context,
	db Queryer,
	token string,
) (*PasswordReset, error) {
	var row PasswordReset
	err := db.QueryRow(ctx, selectPasswordResetByPKSQL, token).Scan(
		&row.Token,
		&row.Email,
		&row.RequestIP,
		&row.RequestTime,
		&row.UserID,
		&row.CompletionIP,
		&row.CompletionTime,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	} else if err != nil {
		return nil, err
	}

	return &row, nil
}

func InsertPasswordReset(ctx context.Context, db Queryer, row *PasswordReset) error {
	args := pgsql.Args{}

	var columns, values []string

	columns = append(columns, `token`)
	values = append(values, args.Use(&row.Token).String())
	columns = append(columns, `email`)
	values = append(values, args.Use(&row.Email).String())
	columns = append(columns, `request_ip`)
	values = append(values, args.Use(&row.RequestIP).String())
	columns = append(columns, `request_time`)
	values = append(values, args.Use(&row.RequestTime).String())
	columns = append(columns, `user_id`)
	values = append(values, args.Use(&row.UserID).String())
	columns = append(columns, `completion_ip`)
	values = append(values, args.Use(&row.CompletionIP).String())
	columns = append(columns, `completion_time`)
	values = append(values, args.Use(&row.CompletionTime).String())

	sql := `insert into "password_resets"(` + strings.Join(columns, ", ") + `)
values(` + strings.Join(values, ",") + `)
returning "token"
  `

	return db.QueryRow(ctx, sql, args.Values()...).Scan(&row.Token)
}

func UpdatePasswordReset(ctx context.Context, db Queryer,
	token string,
	row *PasswordReset,
) error {
	sets := make([]string, 0, 7)
	args := pgsql.Args{}

	sets = append(sets, `token`+"="+args.Use(&row.Token).String())
	sets = append(sets, `email`+"="+args.Use(&row.Email).String())
	sets = append(sets, `request_ip`+"="+args.Use(&row.RequestIP).String())
	sets = append(sets, `request_time`+"="+args.Use(&row.RequestTime).String())
	sets = append(sets, `user_id`+"="+args.Use(&row.UserID).String())
	sets = append(sets, `completion_ip`+"="+args.Use(&row.CompletionIP).String())
	sets = append(sets, `completion_time`+"="+args.Use(&row.CompletionTime).String())

	if len(sets) == 0 {
		return nil
	}

	sql := `update "password_resets" set ` + strings.Join(sets, ", ") + ` where ` + `"token"=` + args.Use(token).String()

	commandTag, err := db.Exec(ctx, sql, args.Values()...)
	if err != nil {
		return err
	}
	if commandTag.RowsAffected() != 1 {
		return ErrNotFound
	}
	return nil
}

func DeletePasswordReset(ctx context.Context, db Queryer,
	token string,
) error {
	args := pgsql.Args{}

	sql := `delete from "password_resets" where ` + `"token"=` + args.Use(token).String()

	commandTag, err := db.Exec(ctx, sql, args.Values()...)
	if err != nil {
		return err
	}
	if commandTag.RowsAffected() != 1 {
		return ErrNotFound
	}
	return nil
}
