package data

// This file is automatically generated by pgxdata.

import (
	"context"

	"errors"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgx/v4"
)

const PGXDATA_VERSION = "0.1.0"

var ErrNotFound = errors.New("not found")

type Queryer interface {
	Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error)
}
